default: &default
  adapter: mysql2
  pool: 20
  timeout: 5000
  port: 3306

development:
  <<: *default
  database: ruby_footsteps_dev
  username: root
  password:

test:
  <<: *default
  database: ruby_footsteps_dev
  username: root
  password:

production:
  <<: *default
  database: ruby_footsteps_dev
  username:
  password:
